In [1]:
#  dataset 2 work done to be here
# ------------------------------------

!pip install pandas numpy matplotlib seaborn scikit-learn openpyxl

Requirement already satisfied: pandas in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (1.26.4)
Requirement already satisfied: matplotlib in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (3.10.9)
Requirement already satisfied: seaborn in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (1.5.2)
Requirement already satisfied: openpyxl in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (from matplotlib) (4.54.1)
Requirement already satisfied: kiwisolver>=1.3.1 in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: packaging>=20.0 in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: scipy>=1.6.0 in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (from scikit-learn) (1.16.2)
Requirement already satisfied: joblib>=1.2.0 in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: et-xmlfile in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in D:\programming\programming\python\age&genderdetection\detectron2_env\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

In [3]:
table1 = pd.read_csv(r"C:\Users\ka843\Coding\AI-Job-Market-Analysis\data\raw\Placement2\indian_student_placement_data.csv")

table2 = pd.read_csv(r"C:\Users\ka843\Coding\AI-Job-Market-Analysis\data\raw\Placement\placement_targets.csv")

table3 = pd.read_csv(r"C:\Users\ka843\Coding\AI-Job-Market-Analysis\data\raw\Placement\indian_engineering_student_placement.csv")

In [14]:
table1["student_id"] = range(1, len(table1) + 1)

In [15]:
table1.head()

,name,email,course,branch,graduation year,company,job role,salary (inr),location,placement date,student_id
0,Yasmin Yadav,ibrar@gmail.com,B.Sc,Civil,2020,Google,Web Developer,808813,Delhi,2024-08-14,1
1,Ritvik Kalla,stuvansaxena@hotmail.com,BCA,EEE,2022,Accenture,Support Engineer,309179,Bangalore,2025-02-05,2
2,Rasha Dewan,neysasule@yahoo.com,B.Com,IT,2023,Accenture,Software Engineer,711614,Hyderabad,2024-03-09,3
3,Indranil Sawhney,sekhonraghav@hotmail.com,BBA,Mechanical,2024,TCS,Consultant,717444,Mumbai,2023-10-18,4
4,Aarav Konda,kurianshray@bava.com,BCA,IT,2023,IBM,Data Analyst,1171796,Hyderabad,2023-11-09,5

In [16]:
table2.head()

   student_id placement_status  salary_lpa
0           1           Placed       14.95
1           2           Placed       14.91
2           3           Placed       17.73
3           4           Placed       14.52
4           5           Placed       15.91

In [ ]:


table3.head()

,Student_ID,gender,branch,cgpa,tenth_percentage,twelfth_percentage,backlogs,study_hours_per_day,attendance_percentage,projects_completed,...,aptitude_skill_rating,hackathons_participated,certifications_count,sleep_hours,stress_level,part_time_job,family_income_level,city_tier,internet_access,extracurricular_involvement
0,1,Male,ECE,8.74,74.0,75.0,0,3.8,71.1,7,...,5,4,5,6.5,8,Yes,Medium,Tier 2,Yes,Medium
1,2,Female,ECE,7.80,75.3,69.7,0,6.3,69.5,5,...,3,4,1,7.1,8,Yes,Medium,Tier 3,Yes,Low
2,3,Female,IT,6.95,62.8,68.3,0,1.5,62.5,8,...,4,6,3,6.1,2,No,Low,Tier 2,Yes,High
3,4,Male,ECE,7.46,57.9,51.4,1,4.7,64.6,6,...,4,2,2,7.3,7,No,Medium,Tier 1,Yes,Low
4,5,Male,IT,6.86,61.3,73.5,2,5.2,75.9,3,...,3,2,1,6.0,7,No,Medium,Tier 1,Yes,Medium

In [17]:
print(table1.columns)

print(table2.columns)

print(table3.columns)

Index(['name', 'email', 'course', 'branch', 'graduation year', 'company',
       'job role', 'salary (inr)', 'location', 'placement date', 'student_id'],
      dtype='str')
Index(['student_id', 'placement_status', 'salary_lpa'], dtype='str')
Index(['student_id', 'gender', 'branch', 'cgpa', 'tenth_percentage',
       'twelfth_percentage', 'backlogs', 'study_hours_per_day',
       'attendance_percentage', 'projects_completed', 'internships_completed',
       'coding_skill_rating', 'communication_skill_rating',
       'aptitude_skill_rating', 'hackathons_participated',
       'certifications_count', 'sleep_hours', 'stress_level', 'part_time_job',
       'family_income_level', 'city_tier', 'internet_access',
       'extracurricular_involvement'],
      dtype='str')

In [18]:
table1.columns = table1.columns.str.strip().str.lower()

table2.columns = table2.columns.str.strip().str.lower()

table3.columns = table3.columns.str.strip().str.lower()

In [19]:
print(table1.columns)

print(table2.columns)

print(table3.columns)

Index(['name', 'email', 'course', 'branch', 'graduation year', 'company',
       'job role', 'salary (inr)', 'location', 'placement date', 'student_id'],
      dtype='str')
Index(['student_id', 'placement_status', 'salary_lpa'], dtype='str')
Index(['student_id', 'gender', 'branch', 'cgpa', 'tenth_percentage',
       'twelfth_percentage', 'backlogs', 'study_hours_per_day',
       'attendance_percentage', 'projects_completed', 'internships_completed',
       'coding_skill_rating', 'communication_skill_rating',
       'aptitude_skill_rating', 'hackathons_participated',
       'certifications_count', 'sleep_hours', 'stress_level', 'part_time_job',
       'family_income_level', 'city_tier', 'internet_access',
       'extracurricular_involvement'],
      dtype='str')

In [20]:
merged_df = pd.merge(
    table3,
    table2,
    on="student_id",
    how="inner"
)

In [21]:
master_df = pd.merge(
    merged_df,
    table1,
    on="student_id",
    how="inner"
)

In [22]:
master_df.head()

master_df.shape

(1000, 35)

In [23]:
master_df.isnull().sum()

student_id                       0
gender                           0
branch_x                         0
cgpa                             0
tenth_percentage                 0
twelfth_percentage               0
backlogs                         0
study_hours_per_day              0
attendance_percentage            0
projects_completed               0
internships_completed            0
coding_skill_rating              0
communication_skill_rating       0
aptitude_skill_rating            0
hackathons_participated          0
certifications_count             0
sleep_hours                      0
stress_level                     0
part_time_job                    0
family_income_level              0
city_tier                        0
internet_access                  0
extracurricular_involvement    202
placement_status                 0
salary_lpa                       0
name                             0
email                            0
course                           0
branch_y                         0
graduation year                  0
company                          0
job role                         0
salary (inr)                     0
location                         0
placement date                   0
dtype: int64

In [25]:
master_df.to_csv(
    r"C:\Users\ka843\Coding\AI-Job-Market-Analysis\data\processed\master_dataset_2.csv",
    index=False
)

In [26]:
data = pd.read_csv(r"C:\Users\ka843\Coding\AI-Job-Market-Analysis\data\processed\master_dataset_2.csv")
data.head()

,student_id,gender,branch_x,cgpa,tenth_percentage,twelfth_percentage,backlogs,study_hours_per_day,attendance_percentage,projects_completed,...,name,email,course,branch_y,graduation year,company,job role,salary (inr),location,placement date
0,1,Male,ECE,8.74,74.0,75.0,0,3.8,71.1,7,...,Yasmin Yadav,ibrar@gmail.com,B.Sc,Civil,2020,Google,Web Developer,808813,Delhi,2024-08-14
1,2,Female,ECE,7.80,75.3,69.7,0,6.3,69.5,5,...,Ritvik Kalla,stuvansaxena@hotmail.com,BCA,EEE,2022,Accenture,Support Engineer,309179,Bangalore,2025-02-05
2,3,Female,IT,6.95,62.8,68.3,0,1.5,62.5,8,...,Rasha Dewan,neysasule@yahoo.com,B.Com,IT,2023,Accenture,Software Engineer,711614,Hyderabad,2024-03-09
3,4,Male,ECE,7.46,57.9,51.4,1,4.7,64.6,6,...,Indranil Sawhney,sekhonraghav@hotmail.com,BBA,Mechanical,2024,TCS,Consultant,717444,Mumbai,2023-10-18
4,5,Male,IT,6.86,61.3,73.5,2,5.2,75.9,3,...,Aarav Konda,kurianshray@bava.com,BCA,IT,2023,IBM,Data Analyst,1171796,Hyderabad,2023-11-09

In [28]:
data['gender'].value_counts()

gender
Male      613
Female    387
Name: count, dtype: int64

In [30]:
data['branch_x'].value_counts()

branch_x
CSE    301
ECE    253
IT     200
ME     154
CE      92
Name: count, dtype: int64

In [ ]:
data['part_time_job'].value_counts()

part_time_job
No     821
Yes    179
Name: count, dtype: int64

In [34]:
data['family_income_level'].value_counts()

family_income_level
Medium    505
Low       292
High      203
Name: count, dtype: int64

In [37]:
data['city_tier'].value_counts()

city_tier
Tier 2    385
Tier 1    319
Tier 3    296
Name: count, dtype: int64

In [38]:
data['internet_access'].value_counts()

internet_access
Yes    886
No     114
Name: count, dtype: int64

In [39]:
data['internet_access'] = data['internet_access'].map({'Yes': 1, 'No': 0})

In [ ]:
data['gender'] = data['gender'].map({'Male': 1, 'Female': 0})